# Generated by Django 2.2.7 on 2020-10-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_inputrestaurant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inputrestaurant',
            new_name='inputanime',
        ),
    ]
