# Generated by Django 2.2.7 on 2020-10-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_auto_20201025_0934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inputanime',
            new_name='inputanime2',
        ),
    ]
